### ISSUE TITLE
Triggers

### ISSUE THREAD

**Issue by adinath-nikam** [Vignesh98/bus-ticket-android-php-mysql#3]
Hey!, Can You Help me With Setting Up Triggers ? You Made Really a Good Project I Just Want How You Set the Triggers For It.
If You Still Have that Trigger Code then Please Can You  Push It ?

**Comment by nvignesh123** [comment]
Unfortunately i dont have this in my drive anymore. But you can check the project report pdf to see how the event is setup to make it recurring

**Comment by adinath-nikam** [comment]
I have done it.Thanks.
